// Logic Lab / Patches: source-backed rectangle partition validator with one clue per patch and declared aspect constraints.
import type { Cell } from "@/game/logicPuzzles/core";
import { keyOf } from "@/game/logicPuzzles/core";

export type PatchShape = "square" | "wide" | "tall" | "free";
export type PatchClue = { id: string; cell: Cell; area: number; shape: PatchShape };
export type Patch = { top: number; left: number; height: number; width: number; clueId: string };
export type PatchesBoard = { rows: number; cols: number; clues: PatchClue[] };
export const patchesBoard: PatchesBoard = { rows: 6, cols: 6, clues: [] };
export const patchesClues: PatchClue[] = [{ id: "A", cell: { row: 0, col: 0 }, area: 4, shape: "square" }, { id: "B", cell: { row: 0, col: 4 }, area: 4, shape: "wide" }, { id: "C", cell: { row: 1, col: 3 }, area: 4, shape: "wide" }, { id: "D", cell: { row: 4, col: 0 }, area: 4, shape: "tall" }, { id: "E", cell: { row: 2, col: 1 }, area: 4, shape: "square" }, { id: "F", cell: { row: 2, col: 4 }, area: 3, shape: "wide" }, { id: "G", cell: { row: 3, col: 3 }, area: 3, shape: "wide" }, { id: "H", cell: { row: 5, col: 1 }, area: 2, shape: "tall" }, { id: "I", cell: { row: 4, col: 2 }, area: 4, shape: "square" }, { id: "J", cell: { row: 4, col: 4 }, area: 2, shape: "tall" }, { id: "K", cell: { row: 5, col: 5 }, area: 2, shape: "tall" }];
patchesBoard.clues = patchesClues;
export const patchesSolution: Patch[] = [{ top: 0, left: 0, height: 2, width: 2, clueId: "A" }, { top: 0, left: 2, height: 1, width: 4, clueId: "B" }, { top: 1, left: 2, height: 1, width: 4, clueId: "C" }, { top: 2, left: 0, height: 4, width: 1, clueId: "D" }, { top: 2, left: 1, height: 2, width: 2, clueId: "E" }, { top: 2, left: 3, height: 1, width: 3, clueId: "F" }, { top: 3, left: 3, height: 1, width: 3, clueId: "G" }, { top: 4, left: 1, height: 2, width: 1, clueId: "H" }, { top: 4, left: 2, height: 2, width: 2, clueId: "I" }, { top: 4, left: 4, height: 2, width: 1, clueId: "J" }, { top: 4, left: 5, height: 2, width: 1, clueId: "K" }];
export const patchCells = (patch: Patch) => Array.from({ length: patch.height * patch.width }, (_, index) => ({ row: patch.top + Math.floor(index / patch.width), col: patch.left + index % patch.width }));
const contains = (patch: Patch, cell: Cell) => cell.row >= patch.top && cell.row < patch.top + patch.height && cell.col >= patch.left && cell.col < patch.left + patch.width;
export function patchMatchesClue(patch: Patch, clue: PatchClue, board: PatchesBoard = patchesBoard) { const area = patch.height * patch.width; const oneClue = board.clues.filter((other) => contains(patch, other.cell)).length === 1; const shapeOk = clue.shape === "free" || clue.shape === "square" && patch.height === patch.width || clue.shape === "wide" && patch.width > patch.height || clue.shape === "tall" && patch.height > patch.width; return area === clue.area && contains(patch, clue.cell) && oneClue && shapeOk; }
export function validPatch(patch: Patch, placed: Patch[], board: PatchesBoard = patchesBoard) { const clue = board.clues.find((item) => item.id === patch.clueId); if (!clue || patch.top < 0 || patch.left < 0 || patch.top + patch.height > board.rows || patch.left + patch.width > board.cols || !patchMatchesClue(patch, clue, board)) return false; const occupied = new Set(placed.flatMap(patchCells).map(keyOf)); return patchCells(patch).every((cell) => !occupied.has(keyOf(cell))); }
export function solvedPatches(placed: Patch[], board: PatchesBoard = patchesBoard) { if (placed.length !== board.clues.length || new Set(placed.map((patch) => patch.clueId)).size !== board.clues.length) return false; const used = new Set<string>(); for (const patch of placed) { if (!validPatch(patch, placed.filter((other) => other !== patch), board)) return false; for (const cell of patchCells(patch)) used.add(keyOf(cell)); } return used.size === board.rows * board.cols; }
export function patchCandidates(clue: PatchClue, board: PatchesBoard = patchesBoard) { const choices: Patch[] = []; for (let height = 1; height <= board.rows; height += 1) for (let width = 1; width <= board.cols; width += 1) for (let top = 0; top <= board.rows - height; top += 1) for (let left = 0; left <= board.cols - width; left += 1) { const patch = { top, left, height, width, clueId: clue.id }; if (patchMatchesClue(patch, clue, board)) choices.push(patch); } return choices; }
export function patchSolutionStats(board: PatchesBoard = patchesBoard, limit = 2) { const candidates = new Map(board.clues.map((clue) => [clue.id, patchCandidates(clue, board)])); let count = 0; let nodes = 0; const search = (placed: Patch[]): void => { if (count >= limit) return; nodes += 1; if (placed.length === board.clues.length) { if (solvedPatches(placed, board)) count += 1; return; } const openClues = board.clues.filter((clue) => !placed.some((patch) => patch.clueId === clue.id)).sort((a, b) => (candidates.get(a.id) || []).length - (candidates.get(b.id) || []).length); const clue = openClues[0]; for (const patch of candidates.get(clue.id) || []) if (validPatch(patch, placed, board)) search([...placed, patch]); }; search([]); return { count, nodes }; }
export function countPatchSolutions(limit = 2, board: PatchesBoard = patchesBoard) { return patchSolutionStats(board, limit).count; }
export { patchesEditionBank, patchesEditionForDate } from "@/game/logicPuzzles/patchesBank";
export type { PatchesEdition, PatchesDifficulty } from "@/game/logicPuzzles/patchesBank";
