// Orbital Workbench / Queens: region-based queen assignment with separate empty, marked, and queen player states; selected daily editions supply their own map and solution.
import { queensEditionBank } from "@/game/logicPuzzles/queensBank";
export type QueenState = "empty" | "marked" | "queen";
export { queensEditionBank, queensEditionForDate } from "@/game/logicPuzzles/queensBank";
export const queensRegions = queensEditionBank[0].regions;
export const queensSolution = queensEditionBank[0].solution;
export function queensViolations(grid: QueenState[][], regionMap = queensRegions) { const invalid = new Set<string>(); const add = (row: number, col: number) => invalid.add(`${row}:${col}`); for (let row = 0; row < 6; row += 1) { const cols = grid[row].map((state, col) => state === "queen" ? col : -1).filter((col) => col >= 0); if (cols.length > 1) cols.forEach((col) => add(row, col)); } for (let col = 0; col < 6; col += 1) { const rows = grid.map((row, index) => row[col] === "queen" ? index : -1).filter((row) => row >= 0); if (rows.length > 1) rows.forEach((row) => add(row, col)); } for (let region = 0; region < 6; region += 1) { const cells: Array<[number, number]> = []; for (let row = 0; row < 6; row += 1) for (let col = 0; col < 6; col += 1) if (regionMap[row][col] === region && grid[row][col] === "queen") cells.push([row, col]); if (cells.length > 1) cells.forEach(([row, col]) => add(row, col)); } const queens: Array<[number, number]> = []; for (let row = 0; row < 6; row += 1) for (let col = 0; col < 6; col += 1) if (grid[row][col] === "queen") queens.push([row, col]); queens.forEach(([row, col], index) => queens.slice(index + 1).forEach(([otherRow, otherCol]) => { if (Math.max(Math.abs(row - otherRow), Math.abs(col - otherCol)) === 1) { add(row, col); add(otherRow, otherCol); } })); return invalid; }
export function solvedQueens(grid: QueenState[][], regionMap = queensRegions) { if (queensViolations(grid, regionMap).size) return false; for (let row = 0; row < 6; row += 1) if (grid[row].filter((state) => state === "queen").length !== 1) return false; for (let col = 0; col < 6; col += 1) if (grid.filter((row) => row[col] === "queen").length !== 1) return false; for (let region = 0; region < 6; region += 1) { let count = 0; for (let row = 0; row < 6; row += 1) for (let col = 0; col < 6; col += 1) if (regionMap[row][col] === region && grid[row][col] === "queen") count += 1; if (count !== 1) return false; } return true; }
export function countQueensSolutionsFor(regionMap: number[][], limit = 2) { let count = 0; const cols = new Set<number>(); const regions = new Set<number>(); const solution: number[] = []; const search = (row: number): void => { if (count >= limit) return; if (row === 6) { count += 1; return; } for (let col = 0; col < 6; col += 1) { const region = regionMap[row][col]; if (cols.has(col) || regions.has(region)) continue; if (solution.some((otherCol, otherRow) => Math.max(Math.abs(otherRow - row), Math.abs(otherCol - col)) === 1)) continue; cols.add(col); regions.add(region); solution.push(col); search(row + 1); solution.pop(); cols.delete(col); regions.delete(region); } }; search(0); return count; }
export function countQueensSolutions(limit = 2) { return countQueensSolutionsFor(queensRegions, limit); }
