// Orbital Workbench: an explicit feedback delivery console using a configured same-origin endpoint or a user-triggered email relay; drafts remain browser-local until the visitor chooses a delivery path.
import AppShell from "@/components/AppShell";
import { contactApiConfigured, submitContact } from "@/lib/contactApi";
import { useState } from "react";

export default function Contact() {
  const [form, setForm] = useState({ name: "", email: "", subject: "Tool feedback", message: "" }); const [status, setStatus] = useState(""); const [sending, setSending] = useState(false);
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!contactApiConfigured) return; setSending(true); setStatus(""); try { const response = await submitContact(form); setStatus(`Feedback received${response.requestId ? ` · ref ${response.requestId}` : ""}.`); setForm({ name: "", email: "", subject: "Tool feedback", message: "" }); } catch (error) { setStatus(error instanceof Error ? error.message : "The feedback request could not be sent."); } finally { setSending(false); } };
  const relayBody = [form.name && `Name: ${form.name}`, form.email && `Email: ${form.email}`, "", form.message].filter(Boolean).join("\n"); const relayHref = `mailto:support@toolboxgalaxy.com?subject=${encodeURIComponent(form.subject || "Toolbox Galaxy feedback")}&body=${encodeURIComponent(relayBody)}`;
  return <AppShell><section className="page-section contact-page"><p className="mono-label text-[#c7f36b]">CONTACT / FEEDBACK DISPATCH</p><h1 className="font-display mt-4 text-5xl font-semibold tracking-[-0.065em]">Send a useful signal.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/62">This release keeps feedback delivery transparent: use the configured Hostinger form link when it is live, or hand your draft to your own email app. Nothing sends automatically.</p><div className="contact-panel"><div className="console-divider"><span>01 · DRAFT</span><span>{contactApiConfigured ? "FORM LINK READY" : "EMAIL RELAY READY"}</span><span>02 · DELIVERY</span></div><aside className="contact-readout" aria-label="Feedback delivery status"><span>DISPATCH STATUS</span><b>{contactApiConfigured ? "SAME-ORIGIN FORM ACTIVE" : "LOCAL DRAFT / EMAIL RELAY"}</b><small>{contactApiConfigured ? "Submitting sends this form to the configured Hostinger endpoint." : "Your draft stays in this tab until you choose Open email relay."}</small></aside><form onSubmit={send} className="contact-form"><label>Name<input required maxLength={80} value={form.name} onChange={(event) => update("name", event.target.value)} /></label><label>Email<input required type="email" maxLength={254} value={form.email} onChange={(event) => update("email", event.target.value)} /></label><label className="wide-field">Subject<input required maxLength={140} value={form.subject} onChange={(event) => update("subject", event.target.value)} /></label><label className="wide-field">Message<textarea required minLength={10} maxLength={3000} rows={7} value={form.message} onChange={(event) => update("message", event.target.value)} /></label><div className="contact-actions">{contactApiConfigured ? <button disabled={sending} className="signal-button">{sending ? "Sending…" : "Send feedback"}</button> : <a data-contact-relay className="signal-button" href={relayHref}>Open email relay</a>}<span aria-live="polite" className="contact-status">{status || (contactApiConfigured ? "Messages are sent only when you select Send feedback." : "The email relay opens your configured mail app with this draft; it does not save or transmit it here.")}</span></div></form></div></section></AppShell>;
}
