import { countQueensSolutionsFor } from "../client/src/game/logicPuzzles/queens";

type RegionMap = number[][];
type Candidate = { solution: number[]; regions: RegionMap; signature: string; symmetrySignature: string; searchNodes: number; regionSizes: number[] };
const size = 6;
const names = ["queens-apollo", "queens-borealis", "queens-celeste", "queens-drift", "queens-equinox", "queens-fathom", "queens-galileo"];
const makeRng = (seed: number) => () => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 0x1_0000_0000; };
const key = (row: number, col: number) => `${row}:${col}`;
const neighbors = (row: number, col: number) => [[row - 1, col], [row + 1, col], [row, col - 1], [row, col + 1]].filter(([nextRow, nextCol]) => nextRow >= 0 && nextRow < size && nextCol >= 0 && nextCol < size) as Array<[number, number]>;
const relabel = (map: RegionMap) => { const labels = new Map<number, number>(); let next = 0; return map.flat().map((value) => { if (!labels.has(value)) labels.set(value, next++); return labels.get(value); }).join(""); };
const transform = (map: RegionMap, mode: number) => Array.from({ length: size }, (_, row) => Array.from({ length: size }, (_, col) => { const [sourceRow, sourceCol] = mode === 0 ? [row, col] : mode === 1 ? [row, size - 1 - col] : mode === 2 ? [size - 1 - row, col] : mode === 3 ? [size - 1 - row, size - 1 - col] : mode === 4 ? [col, row] : mode === 5 ? [size - 1 - col, size - 1 - row] : mode === 6 ? [col, size - 1 - row] : [size - 1 - col, row]; return map[sourceRow][sourceCol]; }));
const symmetrySignature = (map: RegionMap) => Array.from({ length: 8 }, (_, mode) => relabel(transform(map, mode))).sort()[0];
const enumerateSolutions = () => { const solutions: number[][] = []; const used = new Set<number>(); const current: number[] = []; const visit = (row: number) => { if (row === size) { solutions.push([...current]); return; } for (let col = 0; col < size; col += 1) { if (used.has(col) || current.some((otherCol, otherRow) => Math.max(Math.abs(otherRow - row), Math.abs(otherCol - col)) === 1)) continue; used.add(col); current.push(col); visit(row + 1); current.pop(); used.delete(col); } }; visit(0); return solutions; };
const allSolutions = enumerateSolutions();
const searchNodesFor = (regionMap: RegionMap) => { let nodes = 0; const cols = new Set<number>(); const regions = new Set<number>(); const placed: number[] = []; const visit = (row: number) => { nodes += 1; if (row === size) return; for (let col = 0; col < size; col += 1) { const region = regionMap[row][col]; if (cols.has(col) || regions.has(region) || placed.some((otherCol, otherRow) => Math.max(Math.abs(otherRow - row), Math.abs(otherCol - col)) === 1)) continue; cols.add(col); regions.add(region); placed.push(col); visit(row + 1); placed.pop(); cols.delete(col); regions.delete(region); } }; visit(0); return nodes; };
const growRegionMap = (solution: number[], rng: () => number) => { const map = Array.from({ length: size }, () => Array.from({ length: size }, () => -1)); solution.forEach((col, row) => { map[row][col] = row; }); let remaining = size * size - size; while (remaining) { const candidates: Array<{ region: number; row: number; col: number }> = []; for (let row = 0; row < size; row += 1) for (let col = 0; col < size; col += 1) if (map[row][col] >= 0) for (const [nextRow, nextCol] of neighbors(row, col)) if (map[nextRow][nextCol] < 0) candidates.push({ region: map[row][col], row: nextRow, col: nextCol }); if (!candidates.length) return null; const regionSizes = Array.from({ length: size }, (_, region) => map.flat().filter((value) => value === region).length); const preferred = candidates.filter((candidate) => regionSizes[candidate.region] < 8); const pool = preferred.length ? preferred : candidates; const choice = pool[Math.floor(rng() * pool.length)]; map[choice.row][choice.col] = choice.region; remaining -= 1; } const regionSizes = Array.from({ length: size }, (_, region) => map.flat().filter((value) => value === region).length); return regionSizes.every((count) => count >= 3 && count <= 9) ? map : null; };
const candidates: Candidate[] = []; const seenSolution = new Set<string>(); const seenTopology = new Set<string>();
for (let seed = 11; seed < 500000 && candidates.length < 21; seed += 1) { const rng = makeRng(seed); const solution = allSolutions[Math.floor(rng() * allSolutions.length)]; const solutionSignature = solution.join(""); const regions = growRegionMap(solution, rng); if (!regions || seenSolution.has(solutionSignature)) continue; const topology = symmetrySignature(regions); if (seenTopology.has(topology) || countQueensSolutionsFor(regions, 2) !== 1) continue; const regionSizes = Array.from({ length: size }, (_, region) => regions.flat().filter((value) => value === region).length); candidates.push({ solution, regions, signature: relabel(regions), symmetrySignature: topology, searchNodes: searchNodesFor(regions), regionSizes }); seenSolution.add(solutionSignature); seenTopology.add(topology); }
if (candidates.length < names.length) throw new Error(`Only found ${candidates.length} distinct Queens candidates.`);
const ordered = [...candidates].sort((a, b) => a.searchNodes - b.searchNodes); const picks = [ordered[0], ordered[Math.floor(ordered.length * .18)], ordered[Math.floor(ordered.length * .38)], ordered[Math.floor(ordered.length * .56)], ordered[Math.floor(ordered.length * .7)], ordered[Math.floor(ordered.length * .84)], ordered.at(-1)!];
console.log(JSON.stringify(picks.map((candidate, index) => ({ id: names[index], difficulty: index < 2 ? "calm" : index < 5 ? "standard" : "dense", ...candidate })), null, 2));
