type Verdict = { name: string; status: "PASS" | "FAIL"; detail: string };
const preview = "https://3000-icfpg7yyn0cp1goiy9qur-376e73c5.sg1.manus.computer";
const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const verdicts: Verdict[] = [];
const assert = (condition: unknown, name: string, detail: string) => { verdicts.push({ name, status: condition ? "PASS" : "FAIL", detail }); if (!condition) throw new Error(`${name}: ${detail}`); };

class Cdp {
  private socket!: WebSocket; private nextId = 1; private pending = new Map<number, { resolve: (value: any) => void; reject: (reason: Error) => void }>();
  async connect() { const targets = await fetch("http://127.0.0.1:9222/json/list").then((response) => response.json()) as Array<{ type: string; webSocketDebuggerUrl: string; url: string }>; const target = targets.find((item) => item.type === "page" && item.url.includes("3000-icfpg7yyn0cp1goiy9qur-376e73c5")) ?? targets.find((item) => item.type === "page"); if (!target) throw new Error("No debuggable browser page was available."); this.socket = new WebSocket(target.webSocketDebuggerUrl); await new Promise<void>((resolve, reject) => { this.socket.addEventListener("open", () => resolve(), { once: true }); this.socket.addEventListener("error", () => reject(new Error("Could not connect to the browser debugger.")), { once: true }); }); this.socket.addEventListener("message", (event) => { const message = JSON.parse(String(event.data)); if (!message.id) return; const pending = this.pending.get(message.id); if (!pending) return; this.pending.delete(message.id); message.error ? pending.reject(new Error(message.error.message)) : pending.resolve(message.result); }); }
  send(method: string, params: Record<string, unknown> = {}) { return new Promise<any>((resolve, reject) => { const id = this.nextId++; this.pending.set(id, { resolve, reject }); this.socket.send(JSON.stringify({ id, method, params })); }); }
  async evaluate<T>(source: string): Promise<T> { const result = await this.send("Runtime.evaluate", { expression: `(() => { ${source} })()`, awaitPromise: true, returnByValue: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text); return result.result?.value as T; }
  async navigate(path: string) { await this.send("Page.navigate", { url: `${preview}${path}` }); await wait(650); }
  async click(selector: string) { const point = await this.evaluate<{ x: number; y: number } | null>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLElement)) return null; node.scrollIntoView({ block: 'center', inline: 'center', behavior: 'instant' }); const box = node.getBoundingClientRect(); return box.width && box.height ? { x: box.left + box.width / 2, y: box.top + box.height / 2 } : null;`); if (!point) throw new Error(`No clickable visible ${selector}`); await this.send("Input.dispatchMouseEvent", { type: "mousePressed", x: point.x, y: point.y, button: "left", clickCount: 1 }); await this.send("Input.dispatchMouseEvent", { type: "mouseReleased", x: point.x, y: point.y, button: "left", clickCount: 1 }); await wait(120); }
  async replace(selector: string, text: string) { const focused = await this.evaluate<boolean>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLInputElement || node instanceof HTMLTextAreaElement)) return false; node.focus(); node.select(); return document.activeElement === node;`); if (!focused) throw new Error(`Could not focus ${selector}`); await this.send("Input.dispatchKeyEvent", { type: "keyDown", key: "Backspace", code: "Backspace" }); await this.send("Input.dispatchKeyEvent", { type: "keyUp", key: "Backspace", code: "Backspace" }); await this.send("Input.insertText", { text }); await wait(130); }
  async press(selector: string, key: string, code: string) { const focused = await this.evaluate<boolean>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLElement)) return false; node.focus(); return document.activeElement === node;`); if (!focused) throw new Error(`Could not focus ${selector}`); const virtualKeyCode = code === "Enter" ? 13 : code === "Space" ? 32 : 0; const event = { key, code, windowsVirtualKeyCode: virtualKeyCode, nativeVirtualKeyCode: virtualKeyCode, text: code === "Space" ? " " : undefined }; await this.send("Input.dispatchKeyEvent", { type: "rawKeyDown", ...event }); await this.send("Input.dispatchKeyEvent", { type: "keyUp", ...event }); await wait(130); }
  async setNativeControl(selector: string, value: string) { const updated = await this.evaluate<boolean>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLInputElement || node instanceof HTMLSelectElement)) return false; const prototype = node instanceof HTMLSelectElement ? HTMLSelectElement.prototype : HTMLInputElement.prototype; const setter = Object.getOwnPropertyDescriptor(prototype, 'value')?.set; if (!setter) return false; setter.call(node, ${JSON.stringify(value)}); node.dispatchEvent(new Event('input', { bubbles: true })); node.dispatchEvent(new Event('change', { bubbles: true })); return true;`); if (!updated) throw new Error(`Could not update native control ${selector}`); await wait(130); }
  close() { this.socket.close(); }
}

const cdp = new Cdp();
try {
  await cdp.connect();
  await cdp.navigate("/tools/business-days-calculator");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=business-days]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('5 business days');"), "Business Days direct route", "The distinct business-day workspace mounts with a weekday-only normal output.");
  await cdp.click("[data-field=business-include-end]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('4 business days');"), "Business Days pointer option", "A real checkbox click excludes the endpoint and updates the local count.");
  await cdp.setNativeControl("[data-field=business-end]", "2026-08-20"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('End date must be');"), "Business Days invalid range", "A native date-control change event yields the visible reversed-range error.");
  await cdp.click("[data-reset-tool]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('5 business days');"), "Business Days reset", "The pointer reset restores the visible local default.");

  await cdp.navigate("/tools/time-zone-meeting-planner");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=time-zone]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('India');"), "Time Zone Planner direct route", "The timezone-specific workspace mounts independently from Date Difference.");
  await cdp.setNativeControl("[data-field=timezone-source]", "America/New_York"); await cdp.setNativeControl("[data-field=timezone-local]", "2026-03-08T02:30"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('does not occur');"), "Time Zone daylight-saving guard", "A New York native datetime-control change event exposes the local nonexistent-time warning.");
  await cdp.click("[data-reset-tool]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('Kolkata');"), "Time Zone reset", "The pointer reset restores a readable source/target meeting output.");

  await cdp.navigate("/tools/timestamp-converter");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=timestamp]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('2026');"), "Timestamp Converter direct route", "The timestamp-specific workspace mounts with local/UTC readouts.");
  await cdp.replace("[data-field=timestamp-value]", "not-a-time"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('whole Unix timestamp');"), "Timestamp invalid input", "A real keyboard edit gives a visible whole-timestamp validation error.");
  await cdp.click("[data-reset-tool]"); await cdp.click("[data-copy-output]"); assert(await cdp.evaluate("return document.querySelector('[data-copy-output]')?.textContent?.includes('Copied');"), "Timestamp reset and copy", "Pointer reset restores output and pointer copy reports feedback.");

  await cdp.navigate("/tools/text-diff-checker");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=text-diff]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('+ Status: verified');"), "Text Diff direct route", "The line-diff workspace mounts and renders semantic added-line output.");
  await cdp.replace("[data-field=diff-original]", "same\nonly-before"); await cdp.replace("[data-field=diff-revised]", "same\nonly-after"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('- only-before') && document.querySelector('[data-tool-output]')?.textContent?.includes('+ only-after');"), "Text Diff keyboard input", "Two real text edits produce visible added and removed lines.");
  await cdp.click("[data-reset-tool]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('Note: reviewed');"), "Text Diff reset", "Pointer reset restores the audited example field.");

  await cdp.navigate("/tools/find-replace-workspace");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=find-replace]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('3 replacements made');"), "Find / Replace direct route", "The replacement workspace mounts independently from case conversion and text statistics.");
  await cdp.click("[data-field=replace-regex]"); await cdp.replace("[data-field=replace-find]", "["); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('regular expression is not valid');"), "Find / Replace regex safeguard", "A real pointer option and keyboard pattern edit expose the visible invalid-regex guard.");
  await cdp.click("[data-reset-tool]"); await cdp.click("[data-copy-output]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('Beacon') && document.querySelector('[data-copy-output]')?.textContent?.includes('Copied');"), "Find / Replace reset and copy", "Pointer reset restores local literal replacement and copy feedback.");

  await cdp.navigate("/tools/split-bill-tip-calculator");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=split-bill]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('Each person');"), "Split Bill direct route", "The group-bill workspace mounts with a distinct per-person local readout.");
  await cdp.replace("[data-field=split-people]", "3"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('Total for 3');"), "Split Bill keyboard input", "A real keyboard group-size edit updates the visible split.");
  await cdp.replace("[data-field=split-tip]", "150"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('tip from 0%');"), "Split Bill invalid tip", "A real keyboard edit exposes the visible tip-range validation.");
  await cdp.click("[data-reset-tool]"); await cdp.click("[data-copy-output]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('Total for 4') && document.querySelector('[data-copy-output]')?.textContent?.includes('Copied');"), "Split Bill reset and copy", "Pointer reset restores the local group split and copy feedback.");

  await cdp.navigate("/tools/loan-emi-estimate");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=loan-emi]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('Estimated monthly payment') && document.querySelector('.tool-disclaimer')?.textContent?.includes('not financial advice');"), "Loan / EMI direct route", "The fixed-rate estimate workspace mounts with its visible non-advice and exclusions notice.");
  await cdp.replace("[data-field=emi-months]", "0"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('repayment term');"), "Loan / EMI invalid term", "A real keyboard term edit yields the visible estimate validation error.");
  await cdp.click("[data-reset-tool]"); await cdp.click("[data-copy-output]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('Estimated interest') && document.querySelector('[data-copy-output]')?.textContent?.includes('Copied');"), "Loan / EMI reset and copy", "Pointer reset restores the loan estimate and copy feedback.");

  await cdp.navigate("/tools/work-shift-duration");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=work-shift]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('Paid duration') && document.querySelector('[data-tool-output]')?.textContent?.includes('8h 0m');"), "Work Shift direct route", "The shift-duration workspace mounts with a distinct paid-time output.");
  await cdp.setNativeControl("[data-field=shift-start]", "22:00"); await cdp.setNativeControl("[data-field=shift-end]", "06:00"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('crosses midnight');"), "Work Shift overnight path", "Native time-control changes show the distinct overnight marker.");
  await cdp.replace("[data-field=shift-break]", "480"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('break must be shorter');"), "Work Shift invalid break", "A real keyboard break edit yields the visible shift-length guard.");
  await cdp.click("[data-reset-tool]"); await cdp.click("[data-copy-output]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('8h 0m') && document.querySelector('[data-copy-output]')?.textContent?.includes('Copied');"), "Work Shift reset and copy", "Pointer reset restores the same-day duration and copy feedback.");

  await cdp.navigate("/tools/json-csv-converter");
  const converterStorage = await cdp.evaluate<string>("return JSON.stringify(Object.entries(localStorage).sort());");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=json-csv]') instanceof HTMLElement && document.querySelector('[data-tool-output]')?.textContent?.includes('task,owner,done') && document.querySelector('[data-csv-preview] table th[scope=col]') instanceof HTMLTableCellElement;"), "JSON ↔ CSV direct route and semantic preview", "The dedicated conversion workspace mounts with a header-scoped local table preview.");
  await cdp.replace("[data-field=structured-input]", '[{"name":"Ria","note":"two, words"},{"name":"Dev","note":"line\\ntext"}]');
  assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('\"two, words\"') && document.querySelector('[data-csv-preview]')?.textContent?.includes('2 ROWS');"), "JSON ↔ CSV keyboard conversion", "A real keyboard paste-style input serializes CSV commas and refreshes the bounded local preview.");
  await cdp.replace("[data-field=structured-input]", "{"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('valid JSON array');"), "JSON ↔ CSV invalid JSON", "Malformed pasted JSON surfaces a local parse error rather than attempting upload or conversion.");
  await cdp.click("[data-reset-tool]"); await cdp.click("[data-csv-to-json]");
  assert(await cdp.evaluate("return document.querySelector('[data-field=structured-input]') instanceof HTMLTextAreaElement && document.querySelector('[data-field=structured-input]').value.includes('task, owner') && document.querySelector('[data-tool-output]')?.textContent?.includes('\"task\"');"), "JSON ↔ CSV pointer direction switch", "A real pointer press activates the CSV-to-JSON control and loads its independent local example.");
  await cdp.replace("[data-field=structured-input]", "name,name\nRia,Dev"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('headers must be unique');"), "JSON ↔ CSV invalid CSV", "Duplicate CSV headers produce a visible table-contract error.");
  await cdp.click("[data-reset-tool]"); await cdp.evaluate("window.__structuredDownload = ''; const previous = HTMLAnchorElement.prototype.click; HTMLAnchorElement.prototype.click = function() { window.__structuredDownload = this.download; HTMLAnchorElement.prototype.click = previous; };"); await cdp.click("[data-download-output]"); await cdp.click("[data-copy-output]");
  assert(await cdp.evaluate("return window.__structuredDownload === 'toolboxgalaxy-table.json' && document.querySelector('[data-copy-output]')?.textContent?.includes('Copied') && JSON.stringify(Object.entries(localStorage).sort()) === " + JSON.stringify(converterStorage) + ";"), "JSON ↔ CSV copy, download, and no persistence", "Explicit copy/download actions are available while conversion edits do not create a browser-storage record.");

  await cdp.navigate("/tools/csv-viewer-cleaner");
  const viewerStorage = await cdp.evaluate<string>("return JSON.stringify(Object.entries(localStorage).sort());");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=csv-viewer]') instanceof HTMLElement && document.querySelector('[data-csv-preview] table th[scope=col]') instanceof HTMLTableCellElement && document.querySelector('[data-csv-preview]')?.textContent?.includes('2 ROWS');"), "CSV Viewer & Cleaner direct route", "The separate CSV inspection workspace mounts with a semantic, bounded table preview.");
  await cdp.replace("[data-field=csv-input]", "name,note\n Asha , =1+1 \n\n Kiran , done ");
  assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes(\"Asha,'=1+1\") && document.querySelector('[data-csv-preview]')?.textContent?.includes('=1+1') && document.querySelector('[data-csv-preview]')?.textContent?.includes('2 ROWS');"), "CSV Viewer local trim, blank-row removal, and formula text", "The default cleaner trims cells, removes the blank row, and exports a formula-looking cell as spreadsheet text without evaluating it.");
  await cdp.click("[data-field=csv-trim]"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes(' Asha ');"), "CSV Viewer pointer clean toggle", "A real pointer press changes the trim option and immediately updates the local export.");
  await cdp.click("[data-field=csv-trim]"); await cdp.click("[data-apply-clean]"); assert(await cdp.evaluate("return document.querySelector('[data-clean-status]')?.textContent?.includes('current workspace') && document.querySelector('[data-field=csv-input]') instanceof HTMLTextAreaElement && document.querySelector('[data-field=csv-input]').value.includes(\"'=1+1\");"), "CSV Viewer pointer apply clean copy", "Pointer application replaces only the current-tab textarea with the clean export.");
  await cdp.replace("[data-field=csv-input]", "name,task\nAsha"); assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('has 1 cells');"), "CSV Viewer invalid rectangularity", "A short data row receives a visible table-shape error.");
  await cdp.click("[data-reset-tool]"); await cdp.evaluate("window.__structuredDownload = ''; const previous = HTMLAnchorElement.prototype.click; HTMLAnchorElement.prototype.click = function() { window.__structuredDownload = this.download; HTMLAnchorElement.prototype.click = previous; };"); await cdp.click("[data-download-output]"); await cdp.click("[data-copy-output]");
  assert(await cdp.evaluate("return window.__structuredDownload === 'toolboxgalaxy-clean.csv' && document.querySelector('[data-copy-output]')?.textContent?.includes('Copied') && JSON.stringify(Object.entries(localStorage).sort()) === " + JSON.stringify(viewerStorage) + ";"), "CSV Viewer reset, copy, download, and no persistence", "Reset restores the documented example while explicit export actions create no saved CSV state.");
} catch (error) { verdicts.push({ name: "Daily tools browser suite", status: "FAIL", detail: error instanceof Error ? error.message : String(error) }); }
finally { cdp.close(); }
console.table(verdicts);
if (verdicts.some((verdict) => verdict.status === "FAIL")) process.exitCode = 1;
