type Verdict = { name: string; status: "PASS" | "FAIL"; detail: string };
const preview = "https://3000-icfpg7yyn0cp1goiy9qur-376e73c5.sg1.manus.computer";
const fixture = "/home/ubuntu/weekly-personal-best-mobile.png";
const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const verdicts: Verdict[] = [];
const assert = (condition: unknown, name: string, detail: string) => { verdicts.push({ name, status: condition ? "PASS" : "FAIL", detail }); if (!condition) throw new Error(`${name}: ${detail}`); };

class Cdp {
  private socket!: WebSocket; private nextId = 1; private pending = new Map<number, { resolve: (value: any) => void; reject: (reason: Error) => void }>();
  async connect() { const targets = await fetch("http://127.0.0.1:9222/json/list").then((response) => response.json()) as Array<{ type: string; webSocketDebuggerUrl: string; url: string }>; const target = targets.find((item) => item.type === "page" && item.url.includes("3000-icfpg7yyn0cp1goiy9qur-376e73c5")) ?? targets.find((item) => item.type === "page"); if (!target) throw new Error("No debuggable browser page was available."); this.socket = new WebSocket(target.webSocketDebuggerUrl); await new Promise<void>((resolve, reject) => { this.socket.addEventListener("open", () => resolve(), { once: true }); this.socket.addEventListener("error", () => reject(new Error("Could not connect to the browser debugger.")), { once: true }); }); this.socket.addEventListener("message", (event) => { const message = JSON.parse(String(event.data)); if (!message.id) return; const pending = this.pending.get(message.id); if (!pending) return; this.pending.delete(message.id); message.error ? pending.reject(new Error(message.error.message)) : pending.resolve(message.result); }); }
  send(method: string, params: Record<string, unknown> = {}) { return new Promise<any>((resolve, reject) => { const id = this.nextId++; this.pending.set(id, { resolve, reject }); this.socket.send(JSON.stringify({ id, method, params })); }); }
  async evaluate<T>(source: string): Promise<T> { const result = await this.send("Runtime.evaluate", { expression: `(() => { ${source} })()`, awaitPromise: true, returnByValue: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text); return result.result?.value as T; }
  async navigate(path: string) { await this.send("Page.navigate", { url: `${preview}${path}` }); await wait(700); }
  async click(selector: string) { const point = await this.evaluate<{ x: number; y: number } | null>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLElement)) return null; node.scrollIntoView({ block: 'center', inline: 'center', behavior: 'instant' }); const box = node.getBoundingClientRect(); return box.width && box.height ? { x: box.left + box.width / 2, y: box.top + box.height / 2 } : null;`); if (!point) throw new Error(`No clickable visible ${selector}`); await this.send("Input.dispatchMouseEvent", { type: "mousePressed", x: point.x, y: point.y, button: "left", clickCount: 1 }); await this.send("Input.dispatchMouseEvent", { type: "mouseReleased", x: point.x, y: point.y, button: "left", clickCount: 1 }); await wait(160); }
  async replace(selector: string, text: string) { const focused = await this.evaluate<boolean>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLInputElement || node instanceof HTMLTextAreaElement)) return false; node.focus(); node.select(); return document.activeElement === node;`); if (!focused) throw new Error(`Could not focus ${selector}`); await this.send("Input.dispatchKeyEvent", { type: "keyDown", key: "Backspace", code: "Backspace" }); await this.send("Input.dispatchKeyEvent", { type: "keyUp", key: "Backspace", code: "Backspace" }); await this.send("Input.insertText", { text }); await wait(150); }
  async setNativeControl(selector: string, value: string) { const updated = await this.evaluate<boolean>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLInputElement || node instanceof HTMLSelectElement)) return false; const prototype = node instanceof HTMLSelectElement ? HTMLSelectElement.prototype : HTMLInputElement.prototype; const setter = Object.getOwnPropertyDescriptor(prototype, 'value')?.set; if (!setter) return false; setter.call(node, ${JSON.stringify(value)}); node.dispatchEvent(new Event('input', { bubbles: true })); node.dispatchEvent(new Event('change', { bubbles: true })); return true;`); if (!updated) throw new Error(`Could not update native control ${selector}`); await wait(150); }
  async chooseFile(selector: string, path: string) { const documentNode = await this.send("DOM.getDocument"); const query = await this.send("DOM.querySelector", { nodeId: documentNode.root.nodeId, selector }); if (!query.nodeId) throw new Error(`No file input ${selector}`); await this.send("DOM.setFileInputFiles", { files: [path], nodeId: query.nodeId }); await wait(650); }
  close() { this.socket.close(); }
}

const cdp = new Cdp();
try {
  await cdp.connect(); await cdp.navigate("/tools/image-crop-rotate-convert");
  const initialStorage = await cdp.evaluate<string>("return JSON.stringify(Object.entries(localStorage).sort());");
  assert(await cdp.evaluate("return document.querySelector('[data-image-transform]') instanceof HTMLElement && document.querySelector('[data-field=transform-file]') instanceof HTMLInputElement && document.querySelector('.image-transform__empty')?.textContent?.includes('Crop only when you choose');"), "Image Crop / Rotate / Convert direct route", "The separate image workflow mounts with an explicit local-file empty state.");
  await cdp.chooseFile("[data-field=transform-file]", fixture);
  assert(await cdp.evaluate("return document.querySelector('.image-transform__source img') instanceof HTMLImageElement && document.querySelector('[data-render-image]') instanceof HTMLButtonElement && Number(document.querySelector('[data-field=crop-width]')?.value) > 80;"), "Image Crop local file selection", "A real browser file-input selection decodes a bounded still image locally and exposes source-pixel controls.");
  await cdp.replace("[data-field=crop-x]", "12"); await cdp.replace("[data-field=crop-y]", "8"); await cdp.setNativeControl("[data-field=crop-width]", "80"); await cdp.setNativeControl("[data-field=crop-height]", "60");
  assert(await cdp.evaluate("return document.querySelector('[data-field=crop-x]')?.value === '12' && document.querySelector('[data-field=crop-y]')?.value === '8' && document.querySelector('.image-transform__controls')?.textContent?.includes('80 × 60');"), "Image Crop keyboard source coordinates", "Real keyboard and native numeric edits create a precise source-pixel crop window.");
  await cdp.click("[data-rotate-right]"); await cdp.setNativeControl("[data-field=transform-format]", "image/jpeg"); await cdp.setNativeControl("[data-field=transform-quality]", "74");
  assert(await cdp.evaluate("return document.querySelector('.instrument-signature')?.textContent?.includes('60 × 80 OUTPUT') && !document.querySelector('[data-field=transform-quality]')?.hasAttribute('disabled');"), "Image rotation and conversion controls", "A pointer right-turn swaps the planned dimensions and JPG enables the browser-local quality setting.");
  await cdp.click("[data-render-image]"); await wait(700);
  assert(await cdp.evaluate("const output = document.querySelector('.image-transform__output img'); return output instanceof HTMLImageElement && output.naturalWidth === 60 && output.naturalHeight === 80 && document.querySelector('[data-download-image]')?.getAttribute('download')?.endsWith('.jpg');"), "Image Crop local export", "The canvas renders the selected 80×60 crop at a 90° rotation as a 60×80 JPG output.");
  await cdp.evaluate("window.__imageTransformDownload = ''; const anchor = document.querySelector('[data-download-image]'); if (!(anchor instanceof HTMLAnchorElement)) return false; anchor.addEventListener('click', () => { window.__imageTransformDownload = anchor.download; }, { once: true }); return true;"); await cdp.click("[data-download-image]");
  assert(await cdp.evaluate("return window.__imageTransformDownload.endsWith('.jpg');"), "Image Crop explicit download", "The browser-only download action offers a named rendered image and no server handoff.");
  await cdp.click("[data-reset-tool]");
  assert(await cdp.evaluate("return document.querySelector('.image-transform__output')?.textContent?.includes('WAITING FOR EXPORT') && document.querySelector('[data-field=crop-x]')?.value === '0' && JSON.stringify(Object.entries(localStorage).sort()) === " + JSON.stringify(initialStorage) + ";"), "Image Crop reset and no persistence", "Reset restores full-source edit settings and file/crop/output interactions create no local-storage record.");
  await cdp.chooseFile("[data-field=transform-file]", "/home/ubuntu/toolboxgalaxy-rebuild/client/public/favicon.ico");
  assert(await cdp.evaluate("return document.querySelector('[role=alert]')?.textContent?.includes('Choose a PNG, JPG, or WebP image');"), "Image Crop unsupported-format guard", "A real unsupported file selection produces a clear local type limitation without altering storage.");
} catch (error) { verdicts.push({ name: "Image transform browser suite", status: "FAIL", detail: error instanceof Error ? error.message : String(error) }); }
finally { cdp.close(); }
console.table(verdicts);
if (verdicts.some((verdict) => verdict.status === "FAIL")) process.exitCode = 1;
