type Verdict = { name: string; status: "PASS" | "FAIL"; detail: string };
const preview = "https://3000-icfpg7yyn0cp1goiy9qur-376e73c5.sg1.manus.computer";
const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const verdicts: Verdict[] = [];
const assert = (condition: unknown, name: string, detail: string) => { verdicts.push({ name, status: condition ? "PASS" : "FAIL", detail }); if (!condition) throw new Error(`${name}: ${detail}`); };

class Cdp {
  private socket!: WebSocket; private nextId = 1; private pending = new Map<number, { resolve: (value: any) => void; reject: (reason: Error) => void }>();
  async connect() { const targets = await fetch("http://127.0.0.1:9222/json/list").then((response) => response.json()) as Array<{ type: string; webSocketDebuggerUrl: string; url: string }>; const target = targets.find((item) => item.type === "page" && item.url.includes("3000-icfpg7yyn0cp1goiy9qur-376e73c5")) ?? targets.find((item) => item.type === "page"); if (!target) throw new Error("No debuggable browser page was available."); this.socket = new WebSocket(target.webSocketDebuggerUrl); await new Promise<void>((resolve, reject) => { this.socket.addEventListener("open", () => resolve(), { once: true }); this.socket.addEventListener("error", () => reject(new Error("Could not connect to the browser debugger.")), { once: true }); }); this.socket.addEventListener("message", (event) => { const message = JSON.parse(String(event.data)); if (!message.id) return; const pending = this.pending.get(message.id); if (!pending) return; this.pending.delete(message.id); message.error ? pending.reject(new Error(message.error.message)) : pending.resolve(message.result); }); }
  send(method: string, params: Record<string, unknown> = {}) { return new Promise<any>((resolve, reject) => { const id = this.nextId++; this.pending.set(id, { resolve, reject }); this.socket.send(JSON.stringify({ id, method, params })); }); }
  async evaluate<T>(source: string): Promise<T> { const result = await this.send("Runtime.evaluate", { expression: `(() => { ${source} })()`, awaitPromise: true, returnByValue: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text); return result.result?.value as T; }
  async navigate(path: string) { await this.send("Page.navigate", { url: `${preview}${path}` }); await wait(700); }
  async click(selector: string) { const point = await this.evaluate<{ x: number; y: number } | null>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLElement)) return null; node.scrollIntoView({ block: 'center', inline: 'center', behavior: 'instant' }); const box = node.getBoundingClientRect(); return box.width && box.height ? { x: box.left + box.width / 2, y: box.top + box.height / 2 } : null;`); if (!point) throw new Error(`No clickable visible ${selector}`); await this.send("Input.dispatchMouseEvent", { type: "mousePressed", x: point.x, y: point.y, button: "left", clickCount: 1 }); await this.send("Input.dispatchMouseEvent", { type: "mouseReleased", x: point.x, y: point.y, button: "left", clickCount: 1 }); await wait(180); }
  async replace(selector: string, text: string) { const focused = await this.evaluate<boolean>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLInputElement || node instanceof HTMLTextAreaElement)) return false; node.focus(); node.select(); return document.activeElement === node;`); if (!focused) throw new Error(`Could not focus ${selector}`); await this.send("Input.dispatchKeyEvent", { type: "keyDown", key: "Backspace", code: "Backspace" }); await this.send("Input.dispatchKeyEvent", { type: "keyUp", key: "Backspace", code: "Backspace" }); await this.send("Input.insertText", { text }); await wait(170); }
  async setNativeControl(selector: string, value: string) { const updated = await this.evaluate<boolean>(`const node = document.querySelector(${JSON.stringify(selector)}); if (!(node instanceof HTMLInputElement || node instanceof HTMLSelectElement || node instanceof HTMLTextAreaElement)) return false; const prototype = node instanceof HTMLSelectElement ? HTMLSelectElement.prototype : node instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype; const setter = Object.getOwnPropertyDescriptor(prototype, 'value')?.set; if (!setter) return false; setter.call(node, ${JSON.stringify(value)}); node.dispatchEvent(new Event('input', { bubbles: true })); node.dispatchEvent(new Event('change', { bubbles: true })); return true;`); if (!updated) throw new Error(`Could not update native control ${selector}`); await wait(170); }
  close() { this.socket.close(); }
}

const cdp = new Cdp();
try {
  await cdp.connect(); await cdp.navigate("/tools/line-sorter-deduplicator");
  const initialStorage = await cdp.evaluate<string>("return JSON.stringify(Object.entries(localStorage).sort());");
  await cdp.evaluate("window.__lineToolRequests = 0; const originalFetch = window.fetch; window.fetch = (...args) => { window.__lineToolRequests += 1; return originalFetch(...args); }; const originalOpen = XMLHttpRequest.prototype.open; XMLHttpRequest.prototype.open = function(...args) { window.__lineToolRequests += 1; return originalOpen.apply(this, args); }; return true;");
  assert(await cdp.evaluate("return document.querySelector('[data-daily-tool=line-sorter]') instanceof HTMLElement && document.querySelector('[data-field=line-input]') instanceof HTMLTextAreaElement && document.querySelector('[data-tool-output]')?.textContent?.includes('Amber');"), "Line Sorter direct route", "The unique line-processing workspace mounts with a readable current-tab result.");
  await cdp.replace("[data-field=line-input]", "B\nA\nb\n\n  C  ");
  assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent === 'A\\nB\\nC' && document.querySelector('[data-line-stats]')?.textContent?.includes('Repeated removed1') && document.querySelector('[data-line-stats]')?.textContent?.includes('Blank removed1');"), "Line Sorter keyboard text processing", "Real keyboard paste-style text input trims, removes case-insensitive repeats/blanks, and sorts locally.");
  await cdp.click("[data-field=line-case]");
  assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent === 'A\\nB\\nC\\nb';"), "Line Sorter pointer case policy", "A real pointer checkbox change retains case-distinct matching lines before the local sort.");
  await cdp.setNativeControl("[data-field=line-sort]", "none"); await cdp.click("[data-field=line-keep-blank]");
  assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent === 'B\\nA\\nb\\n\\nC';"), "Line Sorter ordering and blank policy", "The explicit first-seen mode and pointer blank-line setting produce the documented local sequence.");
  await cdp.evaluate("window.__lineToolDownload = ''; const anchor = document.querySelector('[data-download-output]'); if (!(anchor instanceof HTMLButtonElement)) return false; const originalClick = HTMLAnchorElement.prototype.click; HTMLAnchorElement.prototype.click = function() { window.__lineToolDownload = this.download; HTMLAnchorElement.prototype.click = originalClick; }; return true;"); await cdp.click("[data-download-output]");
  assert(await cdp.evaluate("return window.__lineToolDownload === 'toolboxgalaxy-lines.txt';"), "Line Sorter explicit download", "A pointer download action creates a named browser-local text export without server processing.");
  await cdp.click("[data-copy-output]");
  assert(await cdp.evaluate("return document.querySelector('[data-copy-output]')?.textContent?.includes('Copied');"), "Line Sorter copy feedback", "The visitor-triggered clipboard action provides visible feedback for the current local output.");
  await cdp.setNativeControl("[data-field=line-input]", "x".repeat(250_001));
  assert(await cdp.evaluate("return document.querySelector('[data-tool-output]')?.textContent?.includes('250,000 characters');"), "Line Sorter input bound", "Oversized current-tab text produces a clear local limit error before output is generated.");
  await cdp.click("[data-reset-tool]");
  assert(await cdp.evaluate("return document.querySelector('[data-field=line-input]')?.value === 'Signal\\nsignal\\nAmber\\n\\n  Beacon \\nSignal' && document.querySelector('[data-field=line-sort]')?.value === 'asc' && JSON.stringify(Object.entries(localStorage).sort()) === " + JSON.stringify(initialStorage) + " && window.__lineToolRequests === 0;"), "Line Sorter reset, no persistence, no request", "Reset restores the documented local example while no text operation creates browser storage or an API request.");
} catch (error) { verdicts.push({ name: "Line sorter browser suite", status: "FAIL", detail: error instanceof Error ? error.message : String(error) }); }
finally { cdp.close(); }
console.table(verdicts);
if (verdicts.some((verdict) => verdict.status === "FAIL")) process.exitCode = 1;
