import { countSudokuSolutions, miniSudokuEditionBank, miniSudokuEditionForDate, solvedSudoku } from "../client/src/game/logicPuzzles/miniSudoku";
import { countTangoSolutions, solvedTango, tangoViolations, type TangoGrid } from "../client/src/game/logicPuzzles/tango";
import { tangoEditionBank, tangoEditionForDate } from "../client/src/game/logicPuzzles/tangoBank";
import { countQueensSolutionsFor, solvedQueens, queensViolations, type QueenState } from "../client/src/game/logicPuzzles/queens";
import { queensEditionBank, queensEditionForDate } from "../client/src/game/logicPuzzles/queensBank";
import { countPatchSolutions, patchCells, patchesSolution, solvedPatches, validPatch, type Patch } from "../client/src/game/logicPuzzles/patches";
import { patchesEditionBank, patchesEditionForDate } from "../client/src/game/logicPuzzles/patchesBank";
import { countZipSolutions, solvedZip, zipEditionBank, zipEditionForDate } from "../client/src/game/logicPuzzles/zip";
import { countWendSolutions, matchesWendWord, solvedWend, validWendPath, wendWords } from "../client/src/game/logicPuzzles/wend";
import { wendEditionBank, wendEditionForDate } from "../client/src/game/logicPuzzles/wendBank";
import { baseToDisplay, displayToBase, getLogicDaily } from "../client/src/game/logicPuzzles/daily";

const assert = (condition: unknown, message: string) => { if (!condition) throw new Error(message); };
const week = (select: (date: string) => { id: string }) => new Set(Array.from({ length: 7 }, (_, index) => select(`2026-08-${String(24 + index).padStart(2, "0")}`).id));
const connected = (map: number[][], region: number) => { const cells = map.flatMap((line, row) => line.map((value, col) => ({ row, col, value })).filter((cell) => cell.value === region)); const queue = cells.length ? [cells[0]] : []; const seen = new Set<string>(); while (queue.length) { const cell = queue.shift()!; const key = `${cell.row}:${cell.col}`; if (seen.has(key)) continue; seen.add(key); [[cell.row - 1, cell.col], [cell.row + 1, cell.col], [cell.row, cell.col - 1], [cell.row, cell.col + 1]].forEach(([row, col]) => { if (map[row]?.[col] === region) queue.push({ row, col, value: region }); }); } return seen.size === cells.length; };

const sudokuSolutions = new Set<string>(); const sudokuMasks = new Set<string>();
assert(miniSudokuEditionBank.length === 7, "Mini Sudoku must ship seven authored editions");
miniSudokuEditionBank.forEach((edition) => { const solution = edition.solution.flat().join(""); const mask = edition.givens.flat().map((value) => value ? "1" : "0").join(""); assert(!sudokuSolutions.has(solution) && !sudokuMasks.has(mask), `${edition.id} must retain distinct solution and clue topology`); sudokuSolutions.add(solution); sudokuMasks.add(mask); assert(solvedSudoku(edition.solution) && countSudokuSolutions(edition.givens) === 1, `${edition.id} must remain uniquely solvable`); });
const sudokuDuplicate = miniSudokuEditionBank[0].solution.map((row) => [...row]); sudokuDuplicate[0][1] = sudokuDuplicate[0][0]; assert(!solvedSudoku(sudokuDuplicate), "Mini Sudoku duplicate must fail"); assert(week(miniSudokuEditionForDate).size === 7, "Seven dates must select all Mini Sudoku editions");

const tangoSolutions = new Set<string>(); const tangoMasks = new Set<string>(); const tangoMaps = new Set<string>();
assert(tangoEditionBank.length === 7, "Tango must ship seven authored editions");
tangoEditionBank.forEach((edition) => { const solution = edition.solution.flat().join(""); const mask = edition.givens.flat().map((value) => value === null ? "0" : "1").join(""); const relations = edition.relations.map((item) => `${item.a.row}:${item.a.col}-${item.b.row}:${item.b.col}:${item.relation}`).sort().join(","); assert(!tangoSolutions.has(solution) && !tangoMasks.has(mask) && !tangoMaps.has(relations), `${edition.id} must retain distinct binary and relation topology`); tangoSolutions.add(solution); tangoMasks.add(mask); tangoMaps.add(relations); assert(solvedTango(edition.solution, edition.relations) && countTangoSolutions(edition.givens, 2, edition.relations) === 1, `${edition.id} must remain uniquely solvable`); const relation = edition.relations[0]; const probe: TangoGrid = Array.from({ length: 6 }, () => Array.from({ length: 6 }, () => null)); probe[relation.a.row][relation.a.col] = 0; probe[relation.b.row][relation.b.col] = relation.relation === "same" ? 1 : 0; assert(tangoViolations(probe, edition.relations).size > 0, `${edition.id} relation mutation must fail`); });
assert(week(tangoEditionForDate).size === 7, "Seven dates must select all Tango editions");

const queensSolutions = new Set<string>(); const queensMaps = new Set<string>(); const queensSymmetry = new Set<string>(); const queensComplexity = new Set<number>();
assert(queensEditionBank.length === 7, "Queens must ship seven authored editions");
queensEditionBank.forEach((edition) => { assert(!queensSolutions.has(edition.solution.join("")) && !queensMaps.has(edition.regionSignature) && !queensSymmetry.has(edition.symmetrySignature), `${edition.id} must retain distinct queen and connected-map topology`); queensSolutions.add(edition.solution.join("")); queensMaps.add(edition.regionSignature); queensSymmetry.add(edition.symmetrySignature); queensComplexity.add(edition.searchNodes); assert(edition.regionSizes.reduce((sum, size) => sum + size, 0) === 36 && edition.regionSizes.every((size) => size >= 3), `${edition.id} must expose six substantive regions`); for (let region = 0; region < 6; region += 1) assert(connected(edition.regions, region), `${edition.id} region ${region + 1} must stay connected`); const grid: QueenState[][] = Array.from({ length: 6 }, () => Array.from({ length: 6 }, () => "empty")); edition.solution.forEach((col, row) => { grid[row][col] = "queen"; }); assert(solvedQueens(grid, edition.regions) && countQueensSolutionsFor(edition.regions) === 1, `${edition.id} must remain uniquely solvable`); const regionCells = edition.regions.flatMap((line, row) => line.map((region, col) => ({ row, col, region }))).filter((cell) => cell.region === 0); const duplicateRegion: QueenState[][] = Array.from({ length: 6 }, () => Array.from({ length: 6 }, () => "empty")); duplicateRegion[regionCells[0].row][regionCells[0].col] = "queen"; duplicateRegion[regionCells[regionCells.length - 1].row][regionCells[regionCells.length - 1].col] = "queen"; assert(queensViolations(duplicateRegion, edition.regions).size > 0, `${edition.id} duplicate-region mutation must fail`); });
assert(queensComplexity.size === 7 && week(queensEditionForDate).size === 7, "Queens must retain distinct search depth and seven-date coverage");

type Transform = (row: number, col: number) => [number, number];
const patchTransforms: Transform[] = [(row, col) => [row, col], (row, col) => [col, 5 - row], (row, col) => [5 - row, 5 - col], (row, col) => [5 - col, row], (row, col) => [row, 5 - col], (row, col) => [5 - row, col], (row, col) => [col, row], (row, col) => [5 - col, 5 - row]];
const patchTopology = (solution: Patch[], transform: Transform) => solution.map((patch) => patchCells(patch).map((cell) => transform(cell.row, cell.col).join(":")).sort().join(",")).sort().join("|");
const canonicalPatchTopology = (solution: Patch[]) => patchTransforms.map((transform) => patchTopology(solution, transform)).sort()[0];
assert(solvedPatches(patchesSolution) && countPatchSolutions() === 1 && !solvedPatches(patchesSolution.slice(0, -1)), "Legacy Patches cover must remain valid, unique, and complete");
const patchesPartitions = new Set<string>(); const patchesSymmetry = new Set<string>(); const patchesClues = new Set<string>(); const patchesComplexity = new Set<number>();
assert(patchesEditionBank.length === 7, "Patches must ship seven authored editions");
patchesEditionBank.forEach((edition) => { const partition = patchTopology(edition.solution, patchTransforms[0]); const canonical = canonicalPatchTopology(edition.solution); const clues = edition.board.clues.map((clue) => `${clue.cell.row}:${clue.cell.col}:${clue.area}:${clue.shape}`).sort().join("|"); assert(!patchesPartitions.has(partition) && !patchesSymmetry.has(canonical) && !patchesClues.has(clues), `${edition.id} must retain distinct clue and non-symmetry-equivalent partition topology`); patchesPartitions.add(partition); patchesSymmetry.add(canonical); patchesClues.add(clues); patchesComplexity.add(edition.searchNodes); assert(edition.board.rows === 6 && edition.board.cols === 6 && edition.clueCount === edition.board.clues.length, `${edition.id} must retain a coherent 6×6 clue field`); assert(solvedPatches(edition.solution, edition.board) && countPatchSolutions(2, edition.board) === 1, `${edition.id} must remain a unique exact cover`); assert(!solvedPatches(edition.solution.slice(0, -1), edition.board), `${edition.id} incomplete cover must fail`); const first = edition.solution[0]; assert(!validPatch({ ...first, height: first.height + 1 }, [], edition.board), `${edition.id} clue-area or boundary mutation must fail`); assert(!validPatch(first, [first], edition.board), `${edition.id} genuine overlap mutation must fail`); });
assert(patchesComplexity.size === 7 && week(patchesEditionForDate).size === 7, "Patches must retain distinct search depth and seven-date coverage");

const zipRoutes = new Set<string>(); assert(zipEditionBank.length === 7, "Zip must ship seven authored editions"); zipEditionBank.forEach((edition) => { const route = edition.solution.map((cell) => `${cell.row}:${cell.col}`).join(","); assert(!zipRoutes.has(route), `${edition.id} must retain a distinct route`); zipRoutes.add(route); assert(solvedZip(edition.solution, edition.board) && countZipSolutions(edition.board) === 1, `${edition.id} must remain uniquely solvable`); assert(!solvedZip([...edition.solution.slice(0, 3), edition.solution[4]], edition.board), `${edition.id} skipped path cell must fail`); }); assert(week(zipEditionForDate).size === 7, "Seven dates must select all Zip editions");

assert(validWendPath(wendWords[0].path) && solvedWend(wendWords) && !solvedWend(wendWords.slice(0, -1)), "Legacy Wend paths must remain orthogonal and exact-cover complete");
const wendWordsSets = new Set<string>(); const wendPaths = new Set<string>(); const wendCandidates = new Set<number>();
assert(wendEditionBank.length === 7, "Wend must ship seven authored editions");
wendEditionBank.forEach((edition) => { assert(!wendWordsSets.has(edition.wordSignature) && !wendPaths.has(edition.pathSignature), `${edition.id} must retain distinct target-word and word-path topology`); wendWordsSets.add(edition.wordSignature); wendPaths.add(edition.pathSignature); wendCandidates.add(edition.candidatePaths); assert(edition.grid.length === 5 && edition.grid.every((line) => line.length === 5), `${edition.id} must retain a 5×5 letter field`); assert(edition.words.every((word) => validWendPath(word.path, edition.grid) && matchesWendWord(word.path, word, edition.grid)), `${edition.id} target paths must spell orthogonally`); assert(solvedWend(edition.words, edition.words) && countWendSolutions(edition.words, edition.grid) === 1, `${edition.id} must remain a unique exact cover`); const start = edition.words[0].path[0]; const nonAdjacent = Array.from({ length: 25 }, (_, index) => ({ row: Math.floor(index / 5), col: index % 5 })).find((cell) => Math.abs(cell.row - start.row) + Math.abs(cell.col - start.col) > 1)!; assert(!validWendPath([start, nonAdjacent], edition.grid), `${edition.id} non-adjacent mutation must fail`); const mutation = edition.grid.map((line) => [...line]); const changed = edition.words[0].path[1]; mutation[changed.row][changed.col] = "?"; assert(!matchesWendWord(edition.words[0].path, edition.words[0], mutation), `${edition.id} letter mutation must fail`); });
assert(wendCandidates.size >= 4 && week(wendEditionForDate).size === 7, "Wend must retain authored branching variation and seven-date coverage");
const daily = getLogicDaily(new Date(2026, 7, 26)); assert(daily.id === getLogicDaily(new Date(2026, 7, 26)).id, "Local daily field must be deterministic"); ([0, 1, 2, 3] as const).forEach((transform) => { const display = baseToDisplay(1, 2, 6, transform); const base = displayToBase(display.row, display.col, 6, transform); assert(base.row === 1 && base.col === 2, "Daily transform must round-trip coordinates"); });
console.log("Logic puzzle validators passed: Mini Sudoku, Tango, Queens, Patches, Zip, Wend.");
