// Orbital Workbench: safe local content tools. Markdown is sanitized before preview or download; contrast math remains entirely in the browser.
import DOMPurify from "dompurify";
import { marked } from "marked";
import { Check, Clipboard, Download, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

function CopyButton({ text }: { text: string }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }; return <button className="copy-button" onClick={copy} disabled={!text}>{copied ? <Check size={15} /> : <Clipboard size={15} />}{copied ? "Copied" : "Copy HTML"}</button>; }

const markdownSample = "# Field notes\n\nBuild **small, reliable** modules.\n\n- Local-first processing\n- Clear results\n- No legacy endpoint\n\n> Previewed safely in your browser.\n\n`const status = 'verified';`";
const sanitizeMarkdown = (input: string) => DOMPurify.sanitize(marked.parse(input, { async: false, gfm: true }) as string, { ALLOWED_TAGS: ["h1", "h2", "h3", "h4", "p", "em", "strong", "code", "pre", "ul", "ol", "li", "a", "blockquote", "hr", "br", "table", "thead", "tbody", "tr", "th", "td"], ALLOWED_ATTR: ["href", "title"] });

export function MarkdownWorkspaceTool() {
  const [input, setInput] = useState(markdownSample); const [mode, setMode] = useState<"preview" | "html">("preview"); const html = useMemo(() => sanitizeMarkdown(input), [input]); const download = () => { const documentText = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Toolbox Galaxy Markdown Export</title><style>body{max-width:760px;margin:48px auto;padding:0 20px;color:#172033;font:17px/1.65 system-ui,sans-serif}pre{overflow:auto;padding:16px;background:#eff3f6;border-radius:8px}code{font-family:ui-monospace,monospace}blockquote{margin-left:0;padding-left:16px;border-left:3px solid #9ad34a;color:#445065}a{color:#2268a6}</style></head><body>${html}</body></html>`; const url = URL.createObjectURL(new Blob([documentText], { type: "text/html;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "toolbox-galaxy-markdown.html"; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="runner-stack markdown-tool"><div className="toggle-row"><button className={mode === "preview" ? "toggle-button toggle-button--active" : "toggle-button"} onClick={() => setMode("preview")}>Safe preview</button><button className={mode === "html" ? "toggle-button toggle-button--active" : "toggle-button"} onClick={() => setMode("html")}>Sanitized HTML</button></div><div className="markdown-tool__grid"><label className="wide-field">Markdown input<textarea value={input} onChange={(event) => setInput(event.target.value)} rows={14} spellCheck="false" /></label><section className="markdown-preview"><div className="telemetry-strip"><span>{mode === "preview" ? "SAFE PREVIEW" : "SANITIZED HTML"}</span><div className="flex gap-2"><CopyButton text={html} /><button className="copy-button" onClick={download}><Download size={15} />Download</button></div></div>{mode === "preview" ? <div className="markdown-preview__content" dangerouslySetInnerHTML={{ __html: html }} /> : <pre>{html}</pre>}</section></div><p className="tool-disclaimer"><ShieldCheck size={15} /> HTML is sanitized before preview and download. Script, style, form, image, and iframe content are removed.</p></div>;
}

type Rgb = [number, number, number];
const parseHex = (value: string): Rgb | null => /^#[0-9a-f]{6}$/i.test(value) ? [parseInt(value.slice(1, 3), 16), parseInt(value.slice(3, 5), 16), parseInt(value.slice(5, 7), 16)] : null;
const luminance = ([r, g, b]: Rgb) => { const toLinear = (channel: number) => { const value = channel / 255; return value <= .03928 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4; }; return .2126 * toLinear(r) + .7152 * toLinear(g) + .0722 * toLinear(b); };
const contrastRatio = (foreground: Rgb, background: Rgb) => { const [light, dark] = [luminance(foreground), luminance(background)].sort((a, b) => b - a); return (light + .05) / (dark + .05); };

export function ContrastCheckerTool() {
  const [foreground, setForeground] = useState("#F4F2EA"); const [background, setBackground] = useState("#11182A"); const ratio = useMemo(() => { const fg = parseHex(foreground); const bg = parseHex(background); return fg && bg ? contrastRatio(fg, bg) : null; }, [foreground, background]); const normal = ratio !== null && ratio >= 4.5; const large = ratio !== null && ratio >= 3; const enhanced = ratio !== null && ratio >= 7;
  return <div className="runner-stack contrast-tool"><div className="contrast-tool__inputs"><label>Text color<div className="color-field"><input type="color" value={foreground} onChange={(event) => setForeground(event.target.value.toUpperCase())} /><input value={foreground} onChange={(event) => setForeground(event.target.value.toUpperCase())} /></div></label><button className="swap-button" onClick={() => { setForeground(background); setBackground(foreground); }} aria-label="Swap text and background colors">⇄</button><label>Background color<div className="color-field"><input type="color" value={background} onChange={(event) => setBackground(event.target.value.toUpperCase())} /><input value={background} onChange={(event) => setBackground(event.target.value.toUpperCase())} /></div></label></div><section className="contrast-preview" style={{ color: foreground, backgroundColor: background }}><p className="mono-label">CONTRAST PREVIEW</p><strong>Readable tools make better work.</strong><span>Normal text · 16px</span></section><div className="contrast-tool__results"><div className="contrast-ratio"><span>CONTRAST RATIO</span><strong>{ratio ? `${ratio.toFixed(2)} : 1` : "Invalid HEX"}</strong></div><div className={normal ? "contrast-check contrast-check--pass" : "contrast-check"}><span>{normal ? "PASS" : "CHECK"}</span>AA normal text · 4.5:1</div><div className={large ? "contrast-check contrast-check--pass" : "contrast-check"}><span>{large ? "PASS" : "CHECK"}</span>AA large text · 3:1</div><div className={enhanced ? "contrast-check contrast-check--pass" : "contrast-check"}><span>{enhanced ? "PASS" : "CHECK"}</span>AAA normal text · 7:1</div></div><p className="tool-disclaimer">Contrast is calculated locally using relative luminance. “Large text” means at least 24px regular or 18.66px bold.</p></div>;
}
