// Orbital Workbench: local-only creation and security utilities with no remote processing or legacy endpoint dependency.
import { Check, Clipboard, Download, FileKey2, ImageUp, LockKeyhole, ShieldCheck } from "lucide-react";
import { ChangeEvent, useEffect, useMemo, useState } from "react";

function CopyValue({ value }: { value: string }) { const [copied, setCopied] = useState(false); const copy = async () => { if (!value) return; await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }; return <button className="copy-button" onClick={copy} disabled={!value}>{copied ? <Check size={15} /> : <Clipboard size={15} />}{copied ? "Copied" : "Copy"}</button>; }

type FaviconSource = { url: string; width: number; height: number; name: string };
type FaviconOutput = { url: string; size: number };
const iconSizes = [16, 32, 48, 180, 512] as const;
const loadImage = (file: File) => new Promise<FaviconSource>((resolve, reject) => { const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => resolve({ url, width: image.naturalWidth, height: image.naturalHeight, name: file.name.replace(/\.[^/.]+$/, "") }); image.onerror = () => { URL.revokeObjectURL(url); reject(new Error("This image cannot be read in the browser.")); }; image.src = url; });

export function FaviconGeneratorTool() {
  const [source, setSource] = useState<FaviconSource | null>(null); const [output, setOutput] = useState<FaviconOutput | null>(null); const [size, setSize] = useState<(typeof iconSizes)[number]>(180); const [error, setError] = useState("");
  useEffect(() => () => { if (source) URL.revokeObjectURL(source.url); }, [source]); useEffect(() => () => { if (output) URL.revokeObjectURL(output.url); }, [output]);
  const choose = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) { setError("Choose a browser-supported image file."); return; } setError(""); try { const next = await loadImage(file); setSource((current) => { if (current) URL.revokeObjectURL(current.url); return next; }); setOutput((current) => { if (current) URL.revokeObjectURL(current.url); return null; }); } catch (reason) { setError(reason instanceof Error ? reason.message : "The image could not be opened."); } };
  const create = async () => { if (!source) return; const image = new Image(); await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("The selected image could not be processed.")); image.src = source.url; }); const canvas = document.createElement("canvas"); canvas.width = size; canvas.height = size; const context = canvas.getContext("2d"); if (!context) { setError("Canvas processing is not available in this browser."); return; } const crop = Math.min(source.width, source.height); const left = (source.width - crop) / 2; const top = (source.height - crop) / 2; context.imageSmoothingEnabled = true; context.imageSmoothingQuality = "high"; context.drawImage(image, left, top, crop, crop, 0, 0, size, size); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((value) => value ? resolve(value) : reject(new Error("PNG export could not be created.")), "image/png")); const url = URL.createObjectURL(blob); setOutput((current) => { if (current) URL.revokeObjectURL(current.url); return { url, size }; }); };
  return <div className="runner-stack favicon-tool"><div className="favicon-upload"><ImageUp size={22} /><div><strong>Load source image locally</strong><p>It will be center-cropped to a square icon. Nothing leaves this tab.</p></div><label className="signal-button image-upload-button">Choose image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={choose} /></label></div>{source && <><div className="favicon-tool__workbench"><figure><figcaption>SOURCE · {source.width} × {source.height}</figcaption><img src={source.url} alt="Favicon source preview" /></figure><div className="favicon-tool__controls"><label>Target size<select value={size} onChange={(event) => setSize(Number(event.target.value) as typeof size)}>{iconSizes.map((value) => <option value={value} key={value}>{value} × {value} PNG</option>)}</select></label><button className="signal-button" onClick={create}>Create favicon</button><p>Use 32px for browser tabs, 180px for Apple touch icons, and 512px for app manifests.</p></div>{output ? <figure><figcaption>OUTPUT · {output.size} × {output.size}</figcaption><div className="favicon-output"><img src={output.url} alt="Generated favicon preview" /><a href={output.url} download={`${source.name}-${output.size}.png`} className="quiet-button"><Download size={16} /> Download PNG</a></div></figure> : <div className="favicon-output-placeholder">Generated icon preview</div>}</div></>}{error && <p className="image-resizer__error" role="alert">{error}</p>}</div>;
}

const hex = (buffer: ArrayBuffer) => Array.from(new Uint8Array(buffer), (byte) => byte.toString(16).padStart(2, "0")).join("");
export function HashGeneratorTool() {
  const [mode, setMode] = useState<"text" | "file">("text"); const [algorithm, setAlgorithm] = useState<"SHA-256" | "SHA-384" | "SHA-512">("SHA-256"); const [text, setText] = useState("Toolbox Galaxy"); const [file, setFile] = useState<File | null>(null); const [result, setResult] = useState(""); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const run = async () => { if (!crypto.subtle) { setError("Web Crypto is unavailable in this browser context."); return; } setWorking(true); setError(""); try { const input = mode === "text" ? new TextEncoder().encode(text) : file ? await file.arrayBuffer() : null; if (!input || (mode === "text" && !text)) throw new Error(mode === "file" ? "Choose a file first." : "Enter text to hash."); const hash = await crypto.subtle.digest(algorithm, input); setResult(hex(hash)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Hashing could not be completed."); } finally { setWorking(false); } };
  return <div className="runner-stack"><div className="toggle-row"><button onClick={() => setMode("text")} className={mode === "text" ? "toggle-button toggle-button--active" : "toggle-button"}>Text</button><button onClick={() => setMode("file")} className={mode === "file" ? "toggle-button toggle-button--active" : "toggle-button"}>File</button></div><label>Algorithm<select value={algorithm} onChange={(event) => setAlgorithm(event.target.value as typeof algorithm)}><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></select></label>{mode === "text" ? <label className="wide-field">Text<textarea value={text} onChange={(event) => setText(event.target.value)} rows={7} spellCheck="false" /></label> : <label className="file-field"><FileKey2 size={19} /><span>{file ? `${file.name} · ${(file.size / 1024).toFixed(1)} KB` : "Choose a file to hash locally"}</span><input type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label>}<div className="flex flex-wrap gap-3"><button onClick={run} disabled={working} className="signal-button"><ShieldCheck size={16} /> {working ? "Hashing…" : `Generate ${algorithm}`}</button><span className="tool-disclaimer">Uses browser cryptography; the selected text or file is never uploaded.</span></div><div className={`result-block ${error ? "result-block--error" : ""}`}><div className="telemetry-strip"><span>{algorithm} DIGEST</span><CopyValue value={result} /></div><pre aria-live="polite">{error || result || "Your local digest will appear here."}</pre></div></div>;
}

type StrengthRule = { label: string; pass: boolean };
export function PasswordStrengthTool() {
  const [password, setPassword] = useState(""); const [visible, setVisible] = useState(false);
  const rules = useMemo<StrengthRule[]>(() => [{ label: "12 or more characters", pass: password.length >= 12 }, { label: "Uppercase letter", pass: /[A-Z]/.test(password) }, { label: "Lowercase letter", pass: /[a-z]/.test(password) }, { label: "Number", pass: /\d/.test(password) }, { label: "Symbol", pass: /[^A-Za-z0-9]/.test(password) }, { label: "No simple repeated character run", pass: password.length > 0 && !/(.)\1\1/.test(password) }], [password]); const points = rules.filter((rule) => rule.pass).length; const label = !password ? "Waiting" : points <= 2 ? "Weak" : points <= 4 ? "Moderate" : points === 5 ? "Strong" : "Excellent";
  return <div className="runner-stack password-audit"><div className="password-audit__top"><label className="wide-field">Password to audit<input type={visible ? "text" : "password"} autoComplete="off" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Type a password locally" /></label><button className="toggle-button" onClick={() => setVisible((current) => !current)}>{visible ? "Hide" : "Show"}</button></div><div className="password-meter" aria-label={`Strength: ${label}`}><div className={`password-meter__fill password-meter__fill--${points}`} style={{ width: `${(points / 6) * 100}%` }} /><span>{label}</span><strong>{points}/6 checks</strong></div><div className="password-rule-grid">{rules.map((rule) => <div className={rule.pass ? "password-rule password-rule--pass" : "password-rule"} key={rule.label}><span>{rule.pass ? "✓" : "○"}</span>{rule.label}</div>)}</div><p className="tool-disclaimer"><LockKeyhole size={15} /> This is a local heuristic, not a breach check or security guarantee. Your password is not transmitted or stored.</p></div>;
}
