// Orbital Workbench: discoverable keyboard reference; it only opens a dialog and never captures tool or game input.
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Kbd, KbdGroup } from "@/components/ui/kbd";
import { Keyboard } from "lucide-react";
import { useEffect, useState } from "react";

const groups = [{ title: "Workbench navigation", rows: [{ keys: ["?"], label: "Open this reference" }, { keys: ["Esc"], label: "Close a reference panel or menu" }, { keys: ["Tab"], label: "Move through visible controls" }] }, { title: "Circuit Shift", rows: [{ keys: ["←", "↑", "→", "↓"], label: "Move the selected relay tile" }, { keys: ["Space"], label: "Rotate the selected relay tile" }, { keys: ["R"], label: "Reset the current board after focus leaves text input" }] }, { title: "Touch equivalent", rows: [{ keys: ["Tap"], label: "Rotate a Circuit Shift tile directly" }, { keys: ["Tap"], label: "Use visible Save, Start, and Sound controls" }] }];
const editable = (target: EventTarget | null) => target instanceof HTMLElement && (target.isContentEditable || ["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName));

export default function ShortcutReference() { const [open, setOpen] = useState(() => new URLSearchParams(window.location.search).has("shortcuts")); useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === "?" && !event.ctrlKey && !event.metaKey && !event.altKey && !editable(event.target)) { event.preventDefault(); setOpen(true); } }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, []); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button type="button" className="shortcut-reference-trigger"><Keyboard size={15} /><span>Shortcut reference</span><Kbd>?</Kbd></button></DialogTrigger><DialogContent className="shortcut-dialog"><DialogHeader><p className="mono-label text-[#c7f36b]">INPUT REFERENCE / LOCAL UI</p><DialogTitle className="font-display">Control signals</DialogTitle><DialogDescription>Shortcuts are guidance only. Typing fields keep their normal behavior, and all actions have visible touch or pointer controls.</DialogDescription></DialogHeader><div className="shortcut-dialog__grid">{groups.map((group) => <section key={group.title} className="shortcut-dialog__group"><h3>{group.title}</h3>{group.rows.map((row) => <div className="shortcut-dialog__row" key={`${group.title}-${row.label}`}><KbdGroup>{row.keys.map((key) => <Kbd key={key}>{key}</Kbd>)}</KbdGroup><span>{row.label}</span></div>)}</section>)}</div><p className="shortcut-dialog__footnote">Circuit Shift sounds remain opt-in. The reference does not send or store keyboard activity.</p></DialogContent></Dialog>; }
